### PR TITLE
Adding power support

### PR DESCRIPTION
**Pull request by ghatwala**
Ensuring this repo builds on ppc64le added the support here.

### CODE REVIEW

**Comment by ghatwala** [comment]
@kinow - have ensured power builds on openjdk8 env only as other jdk env's are not available on travis/power.

**Comment by garydgregory** [comment]
Why do we need this?

**Comment by kinow** [comment]
>Why do we need this?

I assumed @ghatwala wants to ensure commons-pool has been tested on powerpc arch.

If it increases the build time too much, perhaps we can limit to a single configuration (java LTS + powerpc), or if it becomes unstable we can mark as failures ignored, but just report to users whether that works or not?

**Comment by aherbert** [comment]
I made a similar comment on another PR for PPC support. I see the point if the project is using non-Java code such as native JNI calls. If it is pure Java then this amounts to testing the JVM. This is a vendor challenge and not in the scope of commons.

**Comment by kinow** [comment]
Not sure if native code is the only reason for this kind of testing, but that's a good point. I remember seeing issues with different vendors (e.g. IBM) that ended up being fixed in the code, but I don't believe it involved native calls. Though, I remember even more issues with timezone, and we test only 1 timezone in Travis (even in lang that does/or did some date calculation). So if others prefer to keep the scope on 1 JVM only, all good for me :+1:

**Comment by garydgregory** [comment]
Based on 'you don't know if it is broken until you test it', I am OK with adding this now but we should also be OK with dropping it in the future if it makes the build too time consuming or confusing.

**Comment by kinow** [comment]
>should also be OK with dropping it in the future if it makes the build too time consuming or confusing. 

+1

**Pull request merged**
